using UnityEngine;
using UnityEngine.SceneManagement;

public class FinalFlagTrigger : MonoBehaviour
{
    [Header("End Scene Settings")]
    public string thankYouSceneName = "ThankYouScene"; // Nazwa sceny z podziękowaniami

    private bool _hasTriggered = false;

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player") && !_hasTriggered)
        {
            _hasTriggered = true;
            Debug.Log("[FinalFlagTrigger] Gracz dotarł do końca! Zatrzymuję badanie.");

            // 1. Zatrzymujemy zapis do plików CSV w Menedżerze
            if (ExperimentManager.Instance != null)
            {
                ExperimentManager.Instance.StopLogging();
            }

            // 2. Ładujemy scenę końcową
            SceneManager.LoadScene(thankYouSceneName);
        }
    }
}