using UnityEngine;
using UnityEngine.SceneManagement;

public class InstructionController : MonoBehaviour
{
    [Header("Scene Settings")]
    public string nextSceneName = "NeutralScene";

    public void StartNeutralPhase()
    {
        Debug.Log("[InstructionController] Button clicked. Starting Neutral phase.");

        if (ExperimentManager.Instance != null)
        {
            ExperimentManager.Instance.SetPhase("Neutral");
        }
        else
        {
            Debug.LogWarning("[InstructionController] ExperimentManager not found! Start from InitialScene.");
        }

        SceneManager.LoadScene(nextSceneName);
    }
}